name: Build x86_64 Linux (static)

on: push

permissions:
  id-token: "write"
  contents: "write"

jobs:
  build-x86_64-linux:
    name: Build x86_64 Linux (static)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      #- uses: DeterminateSystems/flakehub-cache-action@main
      - name: Build the installer
        run: |
          nix build .#packages.x86_64-linux.nix-installer-static -L
          cp result/bin/nix-installer ./nix-installer-x86_64-linux
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: nix-installer-x86_64-linux
